### ISSUE TITLE
renderFetched causing viewer to be undefined

### ISSUE THREAD

**Issue by ericat** [denvned/isomorphic-relay-router#25]
I am running the Todo example and got this (blocking) warning:

`Warning: RelayContainer: Expected prop`viewer`to be supplied to`TodoApp`, but got`undefined`. Pass an explicit`null`if this is intentional.`

To reproduce, simply add `renderFetched` to the routes file:

```
export default [
    {
        path: '/',
        component: TodoApp,
        queries: ViewerQueries,
        renderFetched: (props) => (React.createElement(TodoApp, props)),
        indexRoute: {
            component: TodoList,
            queries: ViewerQueries,
            prepareParams: () => ({status: 'any'}),
        },
        childRoutes: [
            {
                path: ':status',
                component: TodoList,
                queries: ViewerQueries,
            },
        ],
    },
];
```

Not sure if this is a Relay issue. Thank you!

**Comment by fabiosantoscode** [comment]
This affects me as well. Removing `renderFetched` fixes the problem but in my project I really need that callback. All the workarounds I can think of are dreadful. Any ideas?

**Comment by denvned** [comment]
This is because of an external bug introduced in https://github.com/relay-tools/react-router-relay/pull/130. The line https://github.com/relay-tools/react-router-relay/blob/v0.12.2/src/RouteContainer.js#L52 should be `element = renderFetched({ ...routerProps, ...data }, readyState);`.

The temporary workaround for you might be to write `renderFetched: ({ data, ...routerProps }) => React.createElement(TodoApp, { ...routerProps, ...data }),`.

I plan to upgrade to _react-router-relay_ v0.13, which doesn't have this bug. But note, that in v0.13 there is no `renderFetched` either 😄. It has been replaced with more universal `render` callback.

**Comment by fabiosantoscode** [comment]
Cool, thanks!
