### ISSUE TITLE
How to generate a new schema.json

### ISSUE THREAD

**Issue by fraserxu** [denvned/isomorphic-relay-router#28]
Thanks for the awesome work on the isomorphic relay router!

I got a noob question about how to generate new schema.json from `schema.js` as all the example I can find online are all using the same `updateSchema.js` to update an existing `schema.json`.

I wonder where is the initial `schema.json` come from. I try to run the `updateSchema.js` with an empty `{}` json object, but it told me it's not valid schema.

Do you have any idea how to generate a fresh new schema.json from schema.js. Thanks in advance!

**Comment by mattecapu** [comment]
`schema.json` is nothing but the serialized result of an introspection query onto GraphQL itself. That is, you're asking GraphQL to return a description of the endpoint, and then you're saving this as JSON to that file.
Thus you need
1. A GraphQL schema, ideally the one you're using or it'd be useless
2. A query to introspect GraphQL: easy, because `graphql` provides one out of the box, so you just

``` js
import { introspectionQuery } from 'graphql/utilities'
```

Then you just `fs.writeFileSync(JSON.stringify())` the result.

That said, you don't need a "_initial_" `schema.json`, you need to start with a GraphQL Schema object, which in the example is located [here](https://github.com/denvned/isomorphic-relay-router/blob/master/examples/todo/src/data/schema.js)

**Comment by fraserxu** [comment]
Thanks @mattecapu I understand the process, and I've already have my `schema.js` looks like this:

``` JavaScript
import {
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString
} from 'graphql'

let stat = {
  total_items: '10077840',
  total_users: '6790718'
}

const statType = new GraphQLObjectType({
  name: 'Stat',
  fields: {
    'total_items': {
      type: GraphQLString
    },
    'total_users': {
      type: GraphQLString
    }
  }
})

const QueryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    stat: {
      type: statType,
      resolve: () => {
        return stat
      }
    }
  }
})

export default new GraphQLSchema({
  query: QueryType
})
```

And then I also have the same `updateSchema.js` to update the schema

``` JavaScript
import fs from 'fs'
import path from 'path'
import schema from './schema.js'
import { graphql } from 'graphql'
import { introspectionQuery, printSchema } from 'graphql/utilities'

// Save JSON of full schema introspection for Babel Relay Plugin to use
(async () => {
  var result = await (graphql(schema, introspectionQuery))
  if (result.errors) {
    console.error(
      'ERROR introspecting schema: ',
      JSON.stringify(result.errors, null, 2)
    )
  } else {
    fs.writeFileSync(
      path.join(__dirname, './schema.json'),
      JSON.stringify(result, null, 2)
    )
  }
})()

// Save user readable type system shorthand of schema
fs.writeFileSync(
  path.join(__dirname, './schema.graphql'),
  printSchema(schema)
)

```

And I also have the `babelRelayPlugin.js` which will be used from `.babelrc`

``` JavaScript
var getBabelRelayPlugin = require('babel-relay-plugin')
var schema = require('./schema.json')

module.exports = getBabelRelayPlugin(schema.data)
```

So the steps above presume I have a correct `schema.json` to use to update the schema. Otherwise, it will throw the error because the `schema.json` is wrong.

```
> babel-node ./scripts/updateSchema.js

/Users/fraserxu/src/market-hub/node_modules/babel-relay-plugin/lib/invariant.js:24
    throw new Error(util.format.apply(util, [format].concat(args)));
    ^

Error: Invalid introspection data supplied to `getBabelRelayPlugin()`. The resulting schema is not an object with a `__schema` property.
```

**Comment by fraserxu** [comment]
@mattecapu As the name indicate, it's `updateSchema` rather than `createSchema`, but I don't know how to create a `schema.json` to be able to use `updateSchema`.

**Comment by mattecapu** [comment]
I believe the problem is you're including `babelRelayPlugin.js` as a plugin in your babel configuration, thus you're stumbling upon this chicken-and-egg problem. 
You should first run the script without it. 
To be able to create your first schema.json and in general, to have a more robust building process, I suggest to add a custom env for running updateSchema.js which doesn't include `babelRelayPlugin.js`

**Comment by fraserxu** [comment]
Thanks a lot @mattecapu You are correct, it works after I remove the babelRelayPlugin to generate for the first time.

Do you have any idea why the babelRelayPlugin is need to update the schema? Is it because it will be faster than create a new one from scratch?

**Comment by mattecapu** [comment]
It's not needed, actually. You need it only to compile Relay.QL

**Comment by fraserxu** [comment]
:+1:  Thanks for the explanation @mattecapu ! I have a working code now and it's so nice to know what's going on.

A crash course on isomorphic graphql relay react router all in one day :D

**Comment by mattecapu** [comment]
I know that feeling :) happy to have been helpful
