### ISSUE TITLE
Error: Server request for query `ViewerQueries` failed for the following reasons:

### ISSUE THREAD

**Issue by chrisgwgreen** [denvned/isomorphic-relay-router#6]
Hey denvned,

I've been exploring your module and I really love what you've trying to achieve. I'm trying to create a boilerplate which uses your module isomorphic-relay-router with and graffi-mongoose (https://github.com/RisingStack/graffiti-mongoose) to achieve a fully isomorphic, relay, react stack that uses mongoose/mongo for the database. 

The great thing about graffiti is it generates the schema directly from the mongoose schema. 

I did a pull of your code today however and saw the following error: 

```
Error: Server request for query `ViewerQueries` failed for the following reasons:

1. Argument "first" has invalid value 9007199254740991.
Expected type "Int", found 9007199254740991.
  s:"completed",first:9007199254740991){...__RelayQueryFragmen
                      ^^^
   at /Users/cgwgreen/Desktop/stack/todo/node_modules/react-relay/lib/RelayDefaultNetworkLayer.js:71:23
   at process._tickCallback (node.js:379:9)
```

I'll keep exploring but I thought I'd ask to see if you know what's wrong. 

Cheers

Chris GW Green

**Comment by denvned** [comment]
Hi @chrisgwgreen,

Probably the problem is that 9007199254740991 is too big for `Int` in _graffi-mongoose_ (it is fine in _graphql-js_). You might need to change these lines:
https://github.com/denvned/isomorphic-relay-router/blob/v0.3.1/examples/todo/src/components/TodoList.js#L77
https://github.com/denvned/isomorphic-relay-router/blob/v0.3.1/examples/todo/src/components/TodoListFooter.js#L62

**Comment by denvned** [comment]
Actually, 9007199254740991 recently become too big for _graphql-js_ also. So I fixed the example.
